### ISSUE TITLE
react-draggable not working after build

### ISSUE THREAD

**Issue by pixfirewall** [react-grid-layout/react-draggable#476] opened 2020-05-01 00:45 UTC
i have an issue with react-draggable after build:

TypeError: Super expression must either be null or a function
    at react-draggable.min.js:537
    at react-draggable.min.js:536
    at Module.<anonymous> (react-draggable.min.js:535)
    at n (react-draggable.min.js:15)
    at Object.t.exports (react-draggable.min.js:88)
    at n (react-draggable.min.js:15)
    at t.exports (react-draggable.min.js:51)
    at Object.444 (react-draggable.min.js:5)

**Comment by quantum-noise** [comment] 2020-05-07 12:44
The same error after update react-rnd (which depends on react-draggable) from 10.1.1 to 10.1.9. Perhaps the problem is in react-rnd.

**Comment by STRML** [comment] 2020-05-12 21:09
Duplicate of #472

**Closed as completed by STRML** 2020-05-12 21:09 UTC
