### ISSUE TITLE
Draggable components MAY NOT take up whole horizonal space like <div/>

### ISSUE THREAD

**Issue by promet99** [react-grid-layout/react-draggable#502] opened 2020-07-06 20:13 UTC
Draggable components does take up the whole horizonal space of the place where they were called.
This causes Draggables to be initially rendered on top of each other, which I find quite ridiculous.
Each Draggable was rendered (not next to or slightly lower but) on bottom of other Draggable, making a tower of Draggable.
This is solvable by placing <div/> with very small height and width. 
(I tried 10, and Draggables were rendered exactly 10 pixels on the rightward and downward of the previous component, kindda like windows)

Even though there is an workaround, I think this should be an option of <Drabbable> component.
What do you think?

**Comment by STRML** [comment] 2020-07-07 01:15
Draggables are meant to wrap a component. If they are styled oddly, that's because you placed them oddly. Please brush up on how to use this library.

Closing as this is not a bug.

**Closed as completed by STRML** 2020-07-07 01:15 UTC
